kind: pipeline
type: docker
name: mini-web-deployment

steps:
  - name: build-and-deploy
    image: docker:dind
    volumes:
      - name: docker-socket
        path: /var/run/docker.sock
      - name: app-config
        path: /config
    commands:
      # 检查并创建目录结构
      - mkdir -p /volume1/docker/1panel/apps/local/mini-web/data
      - mkdir -p /volume1/docker/1panel/apps/local/mini-web/logs
      - mkdir -p /volume1/docker/1panel/apps/local/mini-web/configs
      - mkdir -p /volume1/docker/1panel/apps/local/mini-web/screenshots
      # 构建并部署容器
      - docker build -t mini-web:latest .
      - docker stop mini-web-container || true
      - docker rm mini-web-container || true
      - >
        docker run -d --name mini-web-container 
        -p 8090:80
        -v /volume1/docker/1panel/apps/local/mini-web/data:/app/data
        -v /volume1/docker/1panel/apps/local/mini-web/logs:/app/logs
        -v /volume1/docker/1panel/apps/local/mini-web/configs:/app/configs
        -v /volume1/docker/1panel/apps/local/mini-web/screenshots:/tmp/rdp_screenshots
        --restart always
        mini-web:latest

volumes:
  - name: docker-socket
    host:
      path: /var/run/docker.sock
  - name: app-config
    host:
      path: /volume1/docker/1panel/apps/local/mini-web/configs

trigger:
  branch:
    - master